artifactory-pro:
  ports:
  - 80:80/tcp
  - 8081:8081/tcp
  - 443:443/tcp
  - 5000:5000/tcp
  - 5001:5001/tcp
  - 5002:5002/tcp
  restart: on-failure:5
  tty: true
  image: jfrog-docker-registry.bintray.io/artifactory/artifactory-pro:latest
  volumes:
  - /var/opt/jfrog/artifactory/data
  - /var/opt/jfrog/artifactory/logs
  - /var/opt/jfrog/artifactory/backup
  - /var/opt/jfrog/artifactory/etc
  stdin_open: true
